# Generated by Django 3.2 on 2021-04-28 07:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSlip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('total_payment', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('is_fulfilled', models.BooleanField(default=False)),
                ('request_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('request_type', models.CharField(blank=True, max_length=20, null=True)),
                ('total_cost', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.IntegerField(default=0)),
                ('cost', models.FloatField(default=0.0)),
                ('product_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Products.product')),
            ],
        ),
    ]
