# Generated by Django 3.2 on 2021-05-24 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PurchaseRequests', '0002_alter_purchaserequest_prescription_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='is_cancelled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
