# Generated by Django 3.2 on 2021-05-01 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PurchaseRequests', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='note',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='requestitem',
            name='request_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='PurchaseRequests.purchaserequest'),
        ),
    ]
