# Generated by Django 3.2 on 2021-04-28 07:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('frequency', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity_to_buy', models.IntegerField(blank=True, default=0, null=True)),
                ('quantity_to_take', models.IntegerField(blank=True, default=0, null=True)),
                ('first_dose', models.DateTimeField(blank=True, null=True)),
                ('is_ongoing', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('starting_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('prescription_photo', models.FileField(blank=True, null=True, upload_to='prescription_photos')),
                ('prescription_copy', models.FileField(blank=True, null=True, upload_to='prescription_copy')),
                ('is_finished', models.BooleanField(default=False)),
            ],
        ),
    ]
