# Generated by Django 3.2 on 2021-06-14 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prescriptions', '0005_medicinerecord_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='starting_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
