export const ActionTypes = {
      SET_USER: "src/screens/loginScreen/SET_USER",
      SET_USERNAME: "src/screens/loginScreen/SET_USERNAME",
      SET_PASSWORD: "src/screens/loginScreen/SET_PASSWORD",
      SET_PASSWORD_CONFIRM: "src/screens/signupScreen/SET_PASSWORD_CONFIRM",
      SET_JWT_REFRESH: "src/screens/loginScreen/SET_JWT_ACCESS",
      SET_JWT_ACCESS: "src/screens/loginScreen/SET_JWT_ACCESS",
      SET_NAME: "src/screens/signupScreen/SET_NAME",
      SET_NEW_PASSWORD: "src/screens/signupScreen/SET_NEW_PASSWORD",
      SET_CONTACT_NUMBER: "src/screens/signupScreen/SET_CONTACT_NUMBER",
      SET_ADDRESS: "src/screens/signupScreen/SET_ADDRESS", 
      SET_ROLE: "src/screens/signupScreen/SET_ROLE", 
      SET_VALID_ID: "src/screens/signupScreen/SET_VALID_ID", 
      SET_BUSINESS_PERMIT: "src/screens/signupScreen/SET_BUSINESS_PERMIT", 
      SET_MEDICAL_LICENSE: "src/screens/signupScreen/SET_MEDICAL_LICENSE", 
}