# Generated by Django 3.2 on 2021-05-01 11:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('disease_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='product_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='in_stock',
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='GenericName',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('generic_name', models.CharField(blank=True, max_length=200, null=True)),
                ('disease', models.ManyToManyField(to='Products.Disease')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='generic_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Products.genericname'),
        ),
    ]
