name: Django CI

on:
  push:
    branches: [ main, Sprint5 ]
  pull_request:
    branches: [ main, Sprint5 ]

defaults:
  run:
    working-directory: Django/Ayo

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8]
        db: [mysql]
        include:
          - db: ayp_django_db
            MYSQL_ALLOW_EMPTY_PASSWORD: yes
            ports: '3306:3306'
   
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Start Mysql
      if: matrix.db == 'mysql'
      run: sudo systemctl start mysql.service; sudo mysql -u"root" -p"root" -e 'create user ayo@localhost identified by 'ayo'; create database ayo_django_db; grant all privileges on ayo_django_db.* to 'ayo'@'localhost' identified by 'ayo';'
      
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      env:
        DB: ${{matrix.db}}
        DB_USER: ${{matrix.db_user}}
        DB_PASSWORD: ${{matrix.db_password}}
      run: |
        python manage.py test
